### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by brunolouvem** [Bruno-Louvem/chess#1]
## TODO
- [x] Board
- [ ] Movements
  - [x] Pawn
  - [ ] Rook
  - [ ] King
  - [ ] Queen
  - [ ] Bishop
  - [ ] Knight
- [ ] Create game
- [ ] Pion's en passant
- [ ] Castling
- [ ] Checkmate
- [ ] Checking possible checkmate for next turn
- [ ] Pawn's promotion at last line
